version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'  
    ports:
      - 8001:5000
    extra_hosts:
      - 'docker.for.linux.localhost:$DOCKERHOST'   
    volumes:
      - .:/app
    depends_on:
      - db
      
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
        
           
  
      
  db:
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: mykmyk
      MYSQL_PASSWORD: mykmyk
      MYSQL_ROOT_PASSWORD: mykokothe
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306            
